.TH ncc 1 "8 Mar 2003" "Linux" "ncc"
.SH NAME
ncc \- source code analysis
.SH SYNOPSIS
ncc file.c
.SH DESCRIPTION
.B ncc
is a program that can help you hack/study the source code of C programs.
It will report which functions call which other functions, which functions
are called by other functions and what global variables and members of
structures are used by functions. This is useful if you want to analyse
a program and eventually hack it.
.SH USAGE
To use
.B ncc
find the 
.B Makefile
of the program you want to analyse. In the
.B Makefile
locate  the line which sets the C compiler. That is
usually something like
.B CC = gcc
and you must change it to
.B CC = ncc -ncgcc -ncld -ncfabs.
Then compile the application. It may be useful to also replace
.B AR = ar
with
.B AR = nccar
and
.B LD = ld
with
.B LD = nccld
to link nccout object files.
.SH OUTPUT
.B ncc
will produce a file with
.B nccout
extension for every C file analysed.
Then you can use the viewer
.B nccnav
(with 
.B nccnav program.nccout
) to view this data and do your work.
If the procedure of make links object files with "ar" or "ld" you should
manually link the produced
.B .nccout
files.
.SH AUTHORS
The homepage of the ncc project is:
http://students.ceid.upatras.gr/~sxanth/ncc/
.SH SEE ALSO
The documentation included in the package.
